# Server
server.port=8091
# server.servlet.context-path=/api

# CORS
spring.web.cors.allowed-origins=http://localhost:4200

# Path Matching (necessário para o padrão de redirecionamento SPA)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/museuaberto;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=3600s

# Art Institute of Chicago API
artic.api.base-url=https://api.artic.edu/api/v1
artic.api.iiif-base-url=https://www.artic.edu/iiif/2
artic.api.image-size=843,
artic.api.fields=id,title,artist_title,date_display,medium_display,dimensions,image_id,color,thumbnail,description,place_of_origin,style_title,classification_title,artwork_type_title,is_public_domain,artist_display,department_title

# Wikipedia API
wikipedia.api.base-url=https://en.wikipedia.org/api/rest_v1

# Logging
logging.level.com.museuaberto=DEBUG
logging.level.org.springframework.cache=DEBUG
app.base-url=http://localhost:8091